# Fields
ID_FIELD = "_id"
LAST_UPDATED = "_updated"
DATE_CREATED = "_created"
ETAG = "_etag"
VERSION = "_version"
LATEST_VERSION = "_latest_version"
VERSIONS = "_versions"
VERSION_ID_SUFFIX = "_document"

# OAuth2
## Grant Types
AUTHORIZATION_CODE_GRANT = "authorization_code"
IMPLICIT_GRANT = "implicit"
PASSWORD_GRANT = "password"
CLIENT_CREDENTIALS_GRANT = "client_credentials"
REFRESH_TOKEN_GRANT = "refresh_token"
GRANT_TYPES = [AUTHORIZATION_CODE_GRANT, IMPLICIT_GRANT, PASSWORD_GRANT,
               CLIENT_CREDENTIALS_GRANT, REFRESH_TOKEN_GRANT]
## Scopes
SCOPE_FORMAT = "{}:{}"
WRITE_SCOPE = "write"
READ_SCOPE = "read"
ROLE_SCOPE = "role"
USER_SCOPE = "user"
QUEUE_SCOPE = "queue"
WORKER_SCOPE = "worker"
TASKFILE_SCOPE = "taskfile"
TASK_SCOPE = "task"
EXPERIMENT_SCOPE = "experiment"
WRITE_ROLE_SCOPE = SCOPE_FORMAT.format(ROLE_SCOPE, WRITE_SCOPE)
READ_ROLE_SCOPE = SCOPE_FORMAT.format(ROLE_SCOPE, READ_SCOPE)
WRITE_USER_SCOPE = SCOPE_FORMAT.format(USER_SCOPE, WRITE_SCOPE)
READ_USER_SCOPE = SCOPE_FORMAT.format(USER_SCOPE, READ_SCOPE)
WRITE_QUEUE_SCOPE = SCOPE_FORMAT.format(QUEUE_SCOPE, WRITE_SCOPE)
READ_QUEUE_SCOPE = SCOPE_FORMAT.format(QUEUE_SCOPE, READ_SCOPE)
WRITE_WORKER_SCOPE = SCOPE_FORMAT.format(WORKER_SCOPE, WRITE_SCOPE)
READ_WORKER_SCOPE = SCOPE_FORMAT.format(WORKER_SCOPE, READ_SCOPE)
WRITE_TASKFILE_SCOPE = SCOPE_FORMAT.format(TASKFILE_SCOPE, WRITE_SCOPE)
READ_TASKFILE_SCOPE = SCOPE_FORMAT.format(TASKFILE_SCOPE, READ_SCOPE)
WRITE_TASK_SCOPE = SCOPE_FORMAT.format(TASK_SCOPE, WRITE_SCOPE)
READ_TASK_SCOPE = SCOPE_FORMAT.format(TASK_SCOPE, READ_SCOPE)
WRITE_EXPERIMENT_SCOPE = SCOPE_FORMAT.format(EXPERIMENT_SCOPE, WRITE_SCOPE)
READ_EXPERIMENT_SCOPE = SCOPE_FORMAT.format(EXPERIMENT_SCOPE, READ_SCOPE)
ALL_SCOPES = [WRITE_ROLE_SCOPE, READ_ROLE_SCOPE, WRITE_USER_SCOPE, READ_USER_SCOPE, WRITE_QUEUE_SCOPE, READ_QUEUE_SCOPE,
              WRITE_WORKER_SCOPE, READ_WORKER_SCOPE, WRITE_TASKFILE_SCOPE, READ_TASKFILE_SCOPE, WRITE_TASK_SCOPE,
              READ_TASK_SCOPE, WRITE_EXPERIMENT_SCOPE, READ_EXPERIMENT_SCOPE]
ADMIN_SCOPES = ALL_SCOPES
SCIENTIST_SCOPES = [WRITE_TASKFILE_SCOPE, READ_TASKFILE_SCOPE, WRITE_TASK_SCOPE, READ_TASK_SCOPE,
                    WRITE_EXPERIMENT_SCOPE, READ_EXPERIMENT_SCOPE]
## Roles
ADMIN_ROLE = "ADMIN"
SCIENTIST_ROLE = "SCIENTIST"
